apiVersion: v1
kind: Service
metadata:
  name: shopping-api
  labels:
    run: shopping-api
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: NodePort
  selector:
    app: shopping-api
