apiVersion: v1
kind: Service
metadata:
  name: product-api
  labels:
    run: product-api
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app: product-api
