apiVersion: v1
kind: Namespace
metadata:
  name: chaos

---

apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    name: user-api
  namespace: chaos
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: user-api

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: user-api
  namespace: chaos
spec:
  replicas: 3
  selector:
    app: user-api
  template:
    metadata:
      name: user-api
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: lucasnscr/user-api:0.0.1
          ports:
            - containerPort: 8080